### ISSUE TITLE
Add zip of RAML/Schemas as an output

### ISSUE THREAD

**Issue by linusnorton** [assertis/raml-scoop#3]
It would be nice to have an additional zip that contained all the RAML/schemas so that could be distributed to the developers.

**Comment by pies** [comment]
@linusnorton Can it assume that the path to the raml file is also the path to the directory that should be added to the zip file?

**Comment by pies** [comment]
@linusnorton The alternatives are to either try to extract the list of included files from the parser, or to try to extract it from the spec directly. I'll try the parser first I guess.

**Comment by linusnorton** [comment]
Re the paths - yes
